### ISSUE TITLE
Migrate to DiscordAPI org

### ISSUE THREAD

**Issue by RogueException** [meew0/discord-bot-best-practices#12]
Do you think it'd be appropriate to move to this DiscordAPI, which already hosts our community docs? May also increase visibility.

**Comment by meew0** [comment]
Didn't @abalabahaha try this before?

**Comment by abalabahaha** [comment]
That was another thing.

+1

**Comment by Guichaguri** [comment]
:+1:

**Comment by meew0** [comment]
Just noticed I never really replied to this. It could probably be done but I don't really see the point - it being on the API organization will probably only make people think this is official and I doubt it will increase the visibility at all (who ever looks at that organization?).

**Comment by meew0** [comment]
Closing this now, there haven't been any arguments in two months. If there's demand I'll reopen
