### ISSUE TITLE
Customizable Prefixes

### ISSUE THREAD

**Issue by iLexy3** [meew0/discord-bot-best-practices#39]
I decided to make my bot's prefix L! but it turns out that any other letter before the exclamation point works too and I have other bots that use M! so if I were to lets say put M! then my bot and the other bot will both respond. I can't have that. How do I fix it? I tried two different things. I tried this in config.json: 

{
    "token": "DONTWORRYTHISAINTREAL",
    "prefix": "L!"
}

and I tried this on a separate bot in index.js: 

const bot = new Discord.Client();

const token = 'DONTWORRYTHISAINTREAL'; 

const PREFIX = 'K!';   

They both pose the same problem, so what can I do to fix it? FYI I'm very new to this so go easy on me. Lol!

**Comment by FireController1847** [comment]
This is not the place to ask. If you're using Discord.js (which it appears you are), please ask in their Discord server @ https://discord.gg/bRCvFy9
