### ISSUE TITLE
Suggestion for scraping bots

### ISSUE THREAD

**Issue by aequasi** [meew0/discord-bot-best-practices#4]
Suggest to people who want to make a scraping bot, that instead of instantly joining, the bot should ask the person who send the link, if they want the bot

**Comment by anowlcalledjosh** [comment]
...or just have a "join" or "invite" command. That way you don't get all the bots in the channel spamming the channel with confirmation messages.

**Comment by RogueException** [comment]
Several bots spamming every user that posts an invite would discourage invite sharing even more than scraper bots do currently.

I agree that join/invite functions are the only good way to do it.

**Comment by AraHaan** [comment]
or you have the bot only join if the bot owner posts the link.
