### ISSUE TITLE
Keep Bot Online 24/7

### ISSUE THREAD

**Issue by iLexy3** [meew0/discord-bot-best-practices#41]
...So I'm new at creating bots so if this is a dumb question I'm sorry, but my bot keeps going offline the second I exit out of Visual Studio Code. How do I keep my bot online 24/7 without having to be in VSC and without having to keep my computer on all day every day?

**Comment by FireController1847** [comment]
Dude, please stop spamming this repository. This is _not_ the place to ask. The Discord.js people will be able to help you. https://discord.gg/bRCvFy9

**Comment by iLexy3** [comment]
Thanks. I didn't see this reply before my bad.

**Comment by FireController1847** [comment]
You're good. If you can, please close the three issues you just made to help keep the repository clean :)
