### ISSUE TITLE
About/Info command?

### ISSUE THREAD

**Issue by RogueException** [meew0/discord-bot-best-practices#7]
Should we add a rule to encourage bot creators to add an about/info command stating the bot's author and library used?

Unsure about the library part, but knowing who to contact about a bot would be pretty helpful.

**Comment by meew0** [comment]
Yeah, that's a good idea, though I think it should be phrased more as a recommendation than a best practice.

**Comment by actowolfy** [comment]
Would cause a problem if multiple bots used something like !about. Maybe if it's a PM?

**Comment by meew0** [comment]
That's already covered under "unique prefixes" though.
